/**
 * CITYOF-GATE :: MASTER STRUCTURE GENERATOR (ESM)
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = process.cwd();

const STRUCTURE = [
  "models/marketplace",
  "engines/marketplace",
  "engines/street",
  "engines/creator",
  "engines/events",
  "narration/marketplace",
  "events/marketplace",
  "street",
  "street/components",
  "street/styles",
  "panels/marketplace",
  "panels/marketplace/components",
  "panels/marketplace/styles",
  "api/marketplace",
  "hooks/marketplace",
  "routes/marketplace",
  "analytics/marketplace",
  "tests/marketplace",
  "tests/marketplace/models",
  "tests/marketplace/engines",
  "tests/marketplace/api",
  "tests/marketplace/ui"
];

function ensureDir(dir) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) {
    fs.mkdirSync(full, { recursive: true });
    console.log(`📁 Utworzono: ${dir}`);
  } else {
    console.log(`⏭ Istnieje: ${dir}`);
  }

  const readme = path.join(full, "README.md");
  if (!fs.existsSync(readme)) {
    fs.writeFileSync(readme, `# ${dir}\nGenerated by CITYOF-GATE Master Structure Generator.\n`);
  }
}

export function run() {
  console.log("🏗  MASTER STRUCTURE — START");
  STRUCTURE.forEach(ensureDir);
  console.log("🏁 MASTER STRUCTURE — DONE");
}

run();
