// modules/generateScenario.js
const fs = require("fs");
const path = require("path");

const ROOT_DIR = path.join(process.cwd(), "SCENARIOS");

// dostępne typy scenariuszy systemowych
const TYPES = [
  "onboarding",
  "emotional",
  "social",
  "event",
  "progression",
  "crisis",
];

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function createFile(filePath, content) {
  if (fs.existsSync(filePath)) {
    console.log("SKIP (exists):", filePath);
    return;
  }
  fs.writeFileSync(filePath, content, "utf8");
  console.log("CREATE:", filePath);
}

function toKebabCase(name) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function generateScenarioContent(name, type) {
  const idBase = toKebabCase(name) || "step-1";

  return `/**
 * System scenario: ${name}
 * Type: ${type}
 * Generated by modules/generateScenario.js
 */

module.exports = {
  name: "${name}",
  description: "Describe the purpose of this scenario...",
  type: "${type}",
  steps: [
    {
      id: "${idBase}-1",
      trigger: {
        type: "time", // "time" | "event" | "state" | "user-action"
        value: null
      },
      action: {
        festivalEvent: "FESTIVAL_EVENT_NAME",
        payload: {}
      },
      effect: {
        cityStateChange: {},
        reputationChange: 0,
        tokenChange: 0
      },
      visual: {
        overlay: "CITY_INTRO",
        highlight: "DISTRICT_ID",
        message: "Onboarding message for the user..."
      },
      priority: 0,
      duration: 0
    }
  ]
};
`;
}

function printUsage() {
  console.log("Usage:");
  console.log("  node modules/generateScenario.js <type> <name>");
  console.log("");
  console.log("Where <type> is one of:");
  TYPES.forEach((t) => console.log("  - " + t));
  console.log("");
  console.log("Example:");
  console.log('  node modules/generateScenario.js onboarding "Welcome Tour"');
}

function run() {
  const [, , typeArg, ...nameParts] = process.argv;
  if (!typeArg || nameParts.length === 0) {
    printUsage();
    process.exit(1);
  }

  const type = typeArg.toLowerCase();
  if (!TYPES.includes(type)) {
    console.error(`Invalid type: ${type}`);
    console.error("Allowed types:", TYPES.join(", "));
    process.exit(1);
  }

  const name = nameParts.join(" ").trim();
  const fileName = toKebabCase(name) || "scenario";
  const dirPath = path.join(ROOT_DIR, "system", type);
  const filePath = path.join(dirPath, `${fileName}.scenario.js`);

  ensureDir(dirPath);
  const content = generateScenarioContent(name, type);
  createFile(filePath, content);

  console.log("=== Scenario generation complete ===");
}

run();
